#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"/..

for file in $(git diff --cached --name-only --diff-filter=ACMRT | grep "\.[ch]$")
do
    uncrustify -q -f $file -c uncrustify.cfg --check > /dev/null 2> /dev/null
    if [ $? -ne 0 ]; then
        echo "Code not properly formatted. Please run make format and git add again."
        git reset -q HEAD
        exit 1
    fi
done
