#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"/..

git diff --cached --name-only --diff-filter=ACMRT |
  grep "\.[ch]$" |
  xargs -n1 clang-format -style=file -output-replacements-xml |
  grep "<replacement " > /dev/null

if [ $? -eq 0 ]; then
    echo "Code not properly formatted. Please run make format and git add again."
    git reset -q HEAD
    exit 1
fi
